Fixing typos, wording corrections
ScottLogic/Technology-Carbon-Standard pull request #13
Opened 2024-02-15 15:30 UTC by dkrees

2024-02-15 16:09 UTC, nickbarber requested changes
Only other issues i spotted are on the About page there's an open source that needs hyphenating to open-source and it's needs changing to its at "Scott Logic has aligned it’s approach"

2024-02-15 16:09 UTC, nickbarber commented on pages/categories/upstream.md
> +Network routers, switches, wi-fi access points installed
i think Wi-Fi should be capitialised technically. Here and on operational

2024-02-19 13:22 UTC, kdavis04 commented
Minor comment - there's a few places particularly in upstream where the sentences under the subheadings don't end in full stops, whereas they do in the other categories

2024-02-19 15:02 UTC, nickbarber commented
> Only other issues i spotted are on the About page there's an open source that needs hyphenating to open-source and it's needs changing to its at "Scott Logic has aligned it’s approach"

@dkrees did you see this comment

2024-02-20 16:13 UTC, dkrees commented on pages/categories/upstream.md
> +Network routers, switches, wi-fi access points installed
Done

2024-02-20 16:28 UTC, nickbarber approved these changes

2024-02-20 16:29 UTC, merged